#!/usr/bin/zsh
clear ;
docker container rm -f $(docker container ls -a) ;
docker container ls -a ;
docker rmi -f $(docker images -a | grep -v node | grep -v mongo) ;
docker image ls -a ;
docker-compose up ;